import java.util.Scanner;

public class RandomNumberGuessing {
    public static void main(String[] args) {
        //use Math Random that takes a value from 0.00 to 0.99
        double randomDouble=Math.random();
        //multiply random number by 50 and add 1, so the range is between 1 and 50
        randomDouble=randomDouble*50+1;
        //convert the double number into integer
        int randomInt=(int) randomDouble;

        //print system generated random number
        System.out.println("Random number generated by system is :"+randomInt);
        //request user input to guess the random number
        System.out.println("Please guess the random number.");

        //scan and store user input as an integer
        Scanner scanner=new Scanner(System.in);
        int num=scanner.nextInt();

        //while loop to check whether the guess is bigger, smaller or correct
        while (num!=randomInt){
            if (num<randomInt){
                //message if user input is less than random number
                System.out.println("Your number is too small. Try again.");
            }
            if (num>randomInt){
                //message if user input is more than random number
                System.out.println("Your number is too big. Try again.");
            }
            num=scanner.nextInt();//looped request for any consecutive user input
        }
        //message if user input is equal to random number
        System.out.println("This is the correct answer");
    }
}